workflows:
  android-firebase:
    name: Android Firebase Distribution

    environment:
      flutter: 3.44.1

      groups:
        - firebase_credentials

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

        android:
          app_id: $FIREBASE_ANDROID_APP_ID

          groups:
            - testers

          artifact_type: apk